# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  # This workflow contains a single job called "build"
  build:
    container: ghcr.io/pr0methean/inkscapeandimagemagick:main@sha256:963a12cb677238dfe876ccf353d1b3114cbaac511e478881020d263aae55422c
    strategy:
      matrix:
        size: [ 32, 64, 128, 256, 512, 1024, 2048, 4096 ]
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Build Texture Pack
        run: |
          ./build_size.sh ${{ matrix.size }}

      - name: Publish
        uses: actions/upload-artifact@v3
        with:
          name: OcHD
          path: out/*.zip
